### ISSUE TITLE
DIVOC India doesn't work?

### ISSUE THREAD

**Issue by shahns** [Path-Check/who-verifier-app#1]
DIVOC (India) QR codes are reported as `invalid qr`.

**Comment by vitorpamplona** [comment]
Which version are you using? v0.0.12?

**Comment by vitorpamplona** [comment]
Hum.. v0.0.12 is working on all DIVOC codes I have access to. Maybe there is a new version that I am not aware of?

**Comment by vitorpamplona** [comment]
Há. I found one. Looks like some QRs have a `gender` field while others have a `sex` field. I wasn't ready for the `sex` field. I am not sure if this is your problem, but it could be it.

**Comment by shahns** [comment]
As far as I know, some countries are using `sex` and others are using `gender`. But India is using `gender` consistently. 

I think issue was with `uhid` for India. But after adding this to `CredentialSubject`, I can complete the whole process but now certificate is not verified. `RsaSignature2018withPS256Verifier(pubKey).verify(jsonLdObject)` gives false output.

**Comment by vitorpamplona** [comment]
Interesting. What's your credentialSubject ID field? I have seen a lot of things like `did:Aadhaar Card:********xxxx` and that is not a valid DID (also not a valid W3C VC). The java version of the JSONLD rejects the field and thus the package does not validate.  :(

**Comment by shahns** [comment]
mine is `did:Driving License:`.

**Comment by vitorpamplona** [comment]
Yeah, that will never verify on a Java version of W3C VCs. I am not sure if there is a way around it.

**Comment by shahns** [comment]
What is the credentialSubject ID indian dcc for you?

**Comment by vitorpamplona** [comment]
`did:Aadhaar Card:********xxxx`, which is also not a valid DID

**Comment by vitorpamplona** [comment]
The lib rejects spaces within the id field, it removes those bytes from the payload and thus the signature doesn't validate.

**Comment by shahns** [comment]
I see that, for india `https://cowin.gov.in/credentials/vaccination/v1` and `https://cowin.gov.in/credentials/vaccination/v1` schema is also used.

**Comment by vitorpamplona** [comment]
Yep, but the schema is irrelevant. That DID is invalid.

**Comment by vitorpamplona** [comment]
here, they really need to fix this: https://github.com/egovernments/DIVOC/issues/762

**Comment by shahns** [comment]
Then how does javascript implementation validates the certificate? Sorry for the naive question. I am quite new to this field :)

**Comment by vitorpamplona** [comment]
The JS Implementation is crappy. It doesn't validate the did and it generates some RDF codes for it that don't follow any spec.

**Comment by shahns** [comment]
So, removing spaces and capitalization issues, should temporarily (as an HACK) resolve the issue?

**Comment by vitorpamplona** [comment]
It may solve, but I don't have a QR like that to prove it. :(

**Comment by shahns** [comment]
Cant we apply the transformation after reading the QR?

**Comment by vitorpamplona** [comment]
See if the new commit works for you. I replaced one of the Utility classes from JSON-LD and it worked for me.

**Comment by shahns** [comment]
if i am not wrong, `uriutils` is not referenced anywhere. It's still same with me. `Invalid Certificate`. Is it to override `titanium-json-ld`'s implementation?

**Comment by vitorpamplona** [comment]
It is called directly many layers inside the verify function, after the canonicalization. There must be something else with your QR then. Do you see any error message or warning on LogCat?

**Comment by shahns** [comment]
No, I dont see anything on logcat, except an error from okhttp and  `AuthorizationException: {"type":0,"code":3,"errorDescription":"Network error"}` from this application--I suppose this is because i am not using keycloak. Also, he certificate I am using is for first dose.

**Comment by vitorpamplona** [comment]
I think it's something else then. Otherwise, you would see a warning that the did field was not included in the canonicalization. 

Do you mind sharing your QR privately with me?  Signal +1 6173188685

**Comment by vitorpamplona** [comment]
I fixed it on Release 14: https://github.com/Path-Check/who-verifier-app/releases/tag/v0.0.14 

I also opened an issue for https://github.com/filip26/titanium-json-ld/issues/203 to discuss compatibility with the JavaScript JSONLD.

**Comment by shahns** [comment]
Cool! This works now. If I may ask, what is the purpose of react native version of the same app and how it will be different from this?

**Comment by vitorpamplona** [comment]
this app is supported by the WHO and can be used for commercial purposes. The ReactNative app is PathCheck's own app.
